# Generated by Django 5.1 on 2024-08-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('vin_number', models.CharField(max_length=100, unique=True)),
                ('engine_number', models.CharField(max_length=100, unique=True)),
                ('horsepower', models.IntegerField()),
                ('state_number', models.CharField(max_length=50, unique=True)),
                ('tech_passport_number', models.CharField(editable=False, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('category', models.CharField(max_length=10)),
                ('issued_by', models.CharField(max_length=100)),
                ('license_number', models.CharField(editable=False, max_length=100, unique=True)),
            ],
        ),
    ]
